spring.application.name=ZhansayaUniversityApplication
# ??????????? ? ??
spring.datasource.url=jdbc:postgresql://localhost:5432/zhansaya_university_db
spring.datasource.username=postgres
spring.datasource.password=70560

# ????? Hibernate ??? ???????? ???????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true