server.port=8080
spring.application.name=ZhansayaUniversityApplication
# 1. URL ??????????? (????????? ?????? ??? ???? ?????? ?? ?????????)
spring.datasource.url=jdbc:postgresql://localhost:5432/university_db
# 2. ????? ? ?????? ????????????????? PostgreSQL
spring.datasource.username=postgres
spring.datasource.password=70560
# 3. ??????? ? ?????????????? ???? (????? Hibernate ??? ?????? ?????? ???????)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
